#App properties

# ==========================================
# BASE APPLICATION CONFIGURATION
# ==========================================

# This file contains shared configuration used across all environments.
# Environment-specific overrides are defined in:
# - application-dev.properties
# - application-prod.properties

# Active profile is set here or via environment variable
# spring.profiles.active controls which config is loaded






# ===============================
# APPLICATION
# ===============================
spring.application.name=user-authentication-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
# ===============================
# SERVER ERROR HANDLING
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
server.forward-headers-strategy=framework

# ===============================
# API PREFIX (optional but clean)
# ===============================
api.prefix=/api/v1

# ===============================
# APP Base Url (optional but clean)
# ===============================
app.base-url=http://localhost:8080

# ===============================
# Hardcoded Durations
# ===============================
app.token.expiration=15
app.lock.duration=15

# ===============================
# Hardcoded email subject
# ===============================
app.mail.subject=Confirm your email

